name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Verify Project Structure
        run: |
          pwd
          ls -la
          find . -type f | sort

      - name: Build Maven Package
        run: mvn clean package -DskipTests

      - name: Debug Files
        run: |
          pwd
          ls -la
          echo "----- TARGET -----"
          ls -la target || echo "Target folder not found"
            
      - name: Verify JAR Created
        run: |
          echo "Checking target directory..."
          ls -la target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/siddu-009/jenkins-java-project:latest
            ghcr.io/siddu-009/jenkins-java-project:${{ github.sha }}
